services:
  backend:
    build: .  
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
      - MONGO_DB_NAME=Monefflo

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mongodb:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_DATABASE=Monefflo
    ports:
      - "27017:27017"
    volumes:
      - mongo-vol:/data/db

volumes:
  mongo-vol:
