services:
  app:
    build: .
    container_name: moneeflo-app
    environment:
      - NODE_ENV=production
      - PORT=4001
      - MONGODB_URI=mongodb://127.0.0.1:27017/Monefflo
    ports:
      - "4001:4001"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - moneeflo-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - moneeflo-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  moneeflo-network:
    name: moneeflo-network
    driver: bridge

volumes:
  mongo-data:
    name: moneeflo-mongodb-data
